### ISSUE TITLE
HOWTO install? Step by step

### ISSUE THREAD

**Issue by trinione** [Coldzer0/QuickJS-Pascal#2]
Hi,
Before this project gets going in a deep-techie only way I would suggest a 'HOWTO Install. Step by step' be done.

That way many developers and potential developers have the opportunity to get on board with this project.
Thx.

**Comment by Coldzer0** [comment]
Hi @trinione 
First of all sorry for my late reply i was so busy.

And what kind of installation do you mean ?

This project is just a wrapper QuickJS Engine to support FreePascal & Delphi
And i already added a demos in how to use this engine.

If you mean something else please tell in details.

Thanks.

**Comment by trinione** [comment]
Did not see the notification of your reply.

I shall check the demo and see if that is sufficient for a complete newbie.
Thx.
