### ISSUE TITLE
Unicode characters are displayed as multiple chars

### ISSUE THREAD

**Issue by danielrippa** [Coldzer0/QuickJS-Pascal#6]
`console.log(String.fromCharCode(10249)); `
displays: `Γáë` instead of `⠉`

quickjs commit 2e8736f

Using dll from QuickJS-Pascal/LibQJS/Windows/x86_64/
on Windows 10 Pro 2004 build 19041.388 Windows Feature Experience Pack 120.2202.130.0

cmd.exe standalone
cmd on Windows Terminal 1.1.2021.0
cmd Windows Terminal Preview  1.2.2022.0

Cascadia Mono PL, Cascadia Mono, Cascadia Code (2007.001)

**Comment by Coldzer0** [comment]
Hello @danielrippa 

I'll check the code you post.
and if you can test to print the data into another cmd emulator like msys2.
Just to make sure.

And I'll update the core pascal code and the libs because I didn't update the last 2 updates from QuickJS

Will do it tomorrow.

**Comment by danielrippa** [comment]
msys2-x86_64_202007020 on on Windows 10 Pro 2004 build 19041.388 Windows Feature Experience Pack 120.2202.130.0:

`$ /c/tools/js/js.exe test.js`
`Γáë`

**Comment by danielrippa** [comment]
Wasnt related to quickjs.

Got it fixed using:
`SetConsoleOutputCP(CP_UTF8);`

I take this opportunity to say that I really appreciate your work. 
Thank you!
