### ISSUE TITLE
Make file to build QuickJS on all platform

### ISSUE THREAD

**Issue by bernt86** [Coldzer0/QuickJS-Pascal#7]
Hi !
Thanks for your work.
Can you provide the make file to build QuickJS library for all platforms please ?
I aim to compile the library for Raspberry PI, for example...
Thanks

Regards

**Comment by Coldzer0** [comment]
Sorry for late reply, I'm just too busy lately.
I'll combine all build scripts in one and upload it soon.

**Comment by bernt86** [comment]
Hi !
Any news about the build script ?
Thanks for all

Regards

**Comment by synopse** [comment]
+1 for having the build script.
It would be very helpful - even a set of dirty scripts is good, to be used as reference.

**Comment by ClosetGeek-Git** [comment]
> +1 for having the build script. It would be very helpful - even a set of dirty scripts is good, to be used as reference.

bump

**Comment by Coldzer0** [comment]
> > +1 for having the build script. It would be very helpful - even a set of dirty scripts is good, to be used as reference.
> 
> bump

I would recommend using the CMakeLists from https://github.com/quickjs-ng/quickjs
And they have a workflow to automate the compilation https://github.com/quickjs-ng/quickjs/blob/master/.github/workflows/ci.yml

I'll have time next month to update the code to the latest updates happening on QuickJS; I'll try my best.
